.TH popuretext 1 "Translate Toolkit 1.3.0" "" "Translate Toolkit 1.3.0"
.SH NAME
popuretext \- Extracts all the source text from a directory of POT files,
removes po headers and optionally the accelerator keys.
.SH SYNOPSIS
\fBpopuretext\fR \fIpot-dir\fR \fIfile.txt\fR [\fIaccelerator\fR]
.P
Where \fIpot-dir\fR is a directory containing POT files,
\fIfile.txt\fR is a file that contains the output text, and the optional
\fIaccelerator\fR is an accelerator marker to be removed from the text.
.SH DESCRIPTION
Extracts all the source text from a directory of POT files, removing PO
headers and optionally the accelerator keys.

If you want to use other tools to analyse the text within a translation
project to for instance use word frequency to create an initial glossary
then this tool is the starting point to get hold of the pure text.
.SH BUGS
None known
